#pragma once

#include "SIdle.h"
#include "STest.h"
#include "S01.h"
#include "S02.h"
#include "S03.h"
#include "S04.h"
#include "S05.h"
#include "S06.h"
#include "S07.h"
#include "S08.h"
#include "S09.h"
#include "S10.h"
#include "S11.h"